# -*- coding: utf-8 -*-
"""Temmy 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JMNaZeYlMYU3ETTvz6b3RKkLBra4wksc

# PTSD Veterans Data Analysis
"""

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

"""## Setup and Data Loading"""

from google.colab import drive
drive.mount('/content/drive')



"""### Mount Google Drive

### List Data Files
"""

import os

data_path = '/content/drive/MyDrive/Colab Notebooks/Data set/'

if os.path.exists(data_path):
    print(f"Contents of '{data_path}':")
    for item in os.listdir(data_path):
        print(f"- {item}")
else:
    print(f"Error: The path '{data_path}' does not exist. Please verify the folder structure in your Google Drive and update 'data_path'.")

"""### Load CSV Files into DataFrames"""

csv_files = [f for f in os.listdir(data_path) if f.endswith('.csv')]

dataframes = {}

for filename in csv_files:
    file_path = os.path.join(data_path, filename)
    df_name = os.path.splitext(filename)[0] # Get filename without extension
    try:
        dataframes[df_name] = pd.read_csv(file_path)
        print(f"Successfully loaded '{filename}' as '{df_name}'")
    except Exception as e:
        print(f"Error loading '{filename}': {e}")

# Display the head of one of the loaded dataframes as an example
if 'Study_Interventions_20250403' in dataframes:
    print("\nDisplaying the first 5 rows of 'Study_Interventions_20250403':")
    display(dataframes['Study_Interventions_20250403'].head())
elif dataframes:
    # If 'Study_Interventions_20250403' is not there, pick the first one available
    first_df_name = next(iter(dataframes))
    print(f"\nDisplaying the first 5 rows of '{first_df_name}':")
    display(dataframes[first_df_name].head())
else:
    print("No CSV files were loaded.")

"""### Inspect DataFrame Columns"""

print("Binary:\n", dataframes['PTSD_Dichotomous_Outcomes_Between_Arms_20250403'].columns)
print("\nInterventions:\n", dataframes['Study_Interventions_20250403'].columns)
print("\nBaseline:\n", dataframes['Sample_Characteristics_20250403'].columns)

"""## Initial Data Preparation (Legacy/Refactored Steps)"""

df = dataframes['PTSD_Dichotomous_Outcomes_Between_Arms_20250403'].copy()

"""### Initialize DataFrame for Between-Arm Outcomes"""

df['arm_id'] = df['Study ID'].astype(str) + "_" + df['Comparison Arms Designation'].astype(str)
display(df[['Study ID', 'Comparison Arms Designation', 'arm_id']].head())

"""### Prepare Study Characteristics"""

study_char = dataframes['Study_Characteristics_20250403']
features_char = study_char[[
    'Study ID',
    'Trauma Type',
    'Diagnostic Measure',
    'Clinical Setting',
    'Military Status'
]]
display(features_char.head())

"""### Prepare Sample Characteristics"""

sample_char = dataframes['Sample_Characteristics_20250403']
features_demo = sample_char[[
    'Study ID',
    'Veteran Percent',
    'Female Percent',
    'Male Percent'
]]
display(features_demo.head())

"""### Prepare Intervention Features"""

import pandas as pd

# 1. Use the already loaded interventions source file
interventions_df = dataframes['Study_Interventions_20250403'].copy()

# 2. Select the EXACT column names present in the source file
# Note: 'Treatment Duration' is the correct name for the duration field.
# Note: 'Intervention Group' is the correct name for the group/arm field.
features_int = interventions_df[[
    'Study ID',
    'Intervention Group',
    'Standardized Treatment Name',
    'Delivery Method',
    'Treatment Duration'
]].copy()

# 3. Standardise the column names for your master dataset
features_int.columns = [
    'Study ID',
    'Group',
    'Standardized Treatment Name',
    'Delivery Method',
    'duration_fixed'
]

# 4. Clean the keys to ensure a successful merge (stripping trailing spaces)
features_int['Study ID'] = features_int['Study ID'].astype(str).str.strip()
features_int['Group'] = features_int['Group'].astype(str).str.strip()

# 5. Convert duration to numeric (handling non-numeric 'Detail' text if present)
features_int['duration_fixed'] = pd.to_numeric(features_int['duration_fixed'], errors='coerce')

# 6. View the results to confirm
print("Intervention features successfully prepared.")
display(features_int.head())

"""### Merge Study and Arm-Level Data"""

# Study-level merges
df = df.merge(features_char, on='Study ID', how='left')
df = df.merge(features_demo, on='Study ID', how='left')

# Rename 'Comparison Arms Designation' in df to 'Group' to match features_int for merging
df.rename(columns={'Comparison Arms Designation': 'Group'}, inplace=True)

# Arm-level merge
df = df.merge(features_int, on=['Study ID', 'Group'], how='left')

"""### Integrate Baseline Severity (First Attempt)"""

import pandas as pd

# 1. Load the specific source file for within-arm continuous outcomes
baseline_raw = dataframes['PTSD_Continuous_Outcomes_Within_Arms_20250403'].copy()

# 2. Filter strictly for 'Baseline' scores to avoid longitudinal duplicates
# Assessment Point 'Baseline' is the indicator for pre-treatment scores [1-3].
baseline_filtered = baseline_raw[baseline_raw['Assessment Point'] == 'Baseline'].copy()

# 3. FIX: Calculate the Global Median from the SOURCE data
# This ensures we get a real number (like 50 or 60) regardless of the merge success.
global_baseline_median = baseline_filtered['Measure Score Mean'].median()

# 4. Select required columns and standardise the names
# 'Intervention Group' in the source corresponds to 'Group' in your master dataset [1, 2].
baseline_features = baseline_filtered[['Study ID', 'Intervention Group', 'Measure Score Mean']].copy()
baseline_features.columns = ['Study ID', 'Group', 'baseline_severity']

# 5. Essential Cleanup: Strip spaces to ensure the merge finds matches
# Whitespace in IDs is a common cause for 'empty' columns after a merge.
baseline_features['Study ID'] = baseline_features['Study ID'].astype(str).str.strip()
baseline_features['Group'] = baseline_features['Group'].astype(str).str.strip()
df['Study ID'] = df['Study ID'].astype(str).str.strip()
df['Group'] = df['Group'].astype(str).str.strip()

# --- Debugging added: Check merge keys ---
print("\n--- Debugging Baseline Merge ---")
print(f"Unique (Study ID, Group) pairs in df: {df[['Study ID', 'Group']].drop_duplicates().shape[0]}")
print(f"Unique (Study ID, Group) pairs in baseline_features: {baseline_features[['Study ID', 'Group']].drop_duplicates().shape[0]}")

# Temporarily perform an inner merge to see how many rows would actually match
matched_rows = pd.merge(df[['Study ID', 'Group']].drop_duplicates(), baseline_features[['Study ID', 'Group']].drop_duplicates(), on=['Study ID', 'Group'], how='inner')
print(f"Number of (Study ID, Group) pairs that would match in an inner join: {matched_rows.shape[0]}")
print("----------------------------------")
# --- End Debugging ---

# Fix: Remove baseline_severity from df if it exists to avoid MergeError
if 'baseline_severity' in df.columns:
    df = df.drop(columns=['baseline_severity'])

# 6. Merge baseline severity into your comprehensive dataset (df)
df = df.merge(baseline_features, on=['Study ID', 'Group'], how='left')

# Add a check to ensure the 'baseline_severity' column exists after the merge
# This handles cases where the merge might unexpectedly fail to introduce the column.
if 'baseline_severity' not in df.columns:
    df['baseline_severity'] = pd.NA

# 7. Use the Global Median for imputation
# Now, if any veteran arms didn't match, they get the global average.
df['baseline_severity'] = df['baseline_severity'].fillna(global_baseline_median)

print(f"Baseline severity successfully integrated.")
print(f"Used Global Median for imputation: {global_baseline_median}")
print(df[['Study ID', 'Group', 'baseline_severity']].head())

"""### Integrate Continuous Outcomes (First Attempt)"""

# 1. Load the specific file containing continuous outcomes from the dataframes dictionary
outcomes_cont_raw = dataframes['PTSD_Continuous_Outcomes_Between_Arms_20250403'].copy()

# --- DEBUG: Print columns to identify the correct grouping column ---
# print("Columns in outcomes_cont_raw:")
# print(outcomes_cont_raw.columns)
# --- END DEBUG ---

# 2. Select the key columns
continuous_outcomes_features = outcomes_cont_raw[[
    'Study ID',
    'Arms Compared',  # Corrected column name
    'Score Difference 1',
    'EPC Calculated: Comparison Standardized Effect Size'
]].copy()

# 3. Rename columns for consistency and clarity
continuous_outcomes_features.rename(columns={
    'Arms Compared': 'Group',  # Renaming 'Arms Compared' to 'Group'
    'Score Difference 1': 'score_difference_1',
    'EPC Calculated: Comparison Standardized Effect Size': 'es_comparison'
}, inplace=True);

# 4. Handle potential conflicting columns before merging
# Identify columns in continuous_outcomes_features that are not merge keys
cols_to_merge = ['score_difference_1', 'es_comparison']

# Drop these columns and their potentially suffixed versions from df if they exist
for col in cols_to_merge:
    if col in df.columns:
        df = df.drop(columns=[col])
    if f'{col}_x' in df.columns: # Check for _x suffix from previous merges
        df = df.drop(columns=[f'{col}_x'])
    if f'{col}_y' in df.columns: # Check for _y suffix from previous merges
        df = df.drop(columns=[f'{col}_y'])

# 5. Merge into your existing comprehensive dataset (df)
df = df.merge(continuous_outcomes_features, on=['Study ID', 'Group'], how='left')

print("Continuous outcomes successfully integrated.")
# Display the head with the new columns to verify
print(df[['Study ID', 'Group', 'score_difference_1', 'es_comparison']].head())

"""### Apply Veteran Filter (First Attempt)"""

df = df[
    (df['Veteran Percent'] > 0) |
    (df['Military Status'] == 'Veteran')
]

"""### Integrate Binary Outcome (First Attempt)"""

import pandas as pd

# 1. Load the within-arm dichotomous outcomes file
# This file contains the 'Percent Achieved Diagnostic Change' column
dichot_within = dataframes['PTSD_Dichotomous_Outcomes_Within_Arms_20250403'].copy()

# 2. Filter for primary success at the End of Treatment
# Assessment Point '0' represents end-of-treatment results
# Diagnostic Change Definition Number 1 is typically the primary outcome
dichot_filtered = dichot_within[
    (dichot_within['Assessment Point'] == '0') &
    (dichot_within['Diagnostic Change Definition Number'] == 1)
].copy()

# 3. Standardise the keys and select the target column
# 'Intervention Group' in this file corresponds to 'Group' in your master dataset
dichot_subset = dichot_filtered[['Study ID', 'Intervention Group', 'Percent Achieved Diagnostic Change']].copy()
dichot_subset.columns = ['Study ID', 'Group', 'Percent Achieved Diagnostic Change']

# 4. Clean keys to ensure a perfect merge
dichot_subset['Study ID'] = dichot_subset['Study ID'].astype(str).str.strip()
dichot_subset['Group'] = dichot_subset['Group'].astype(str).str.strip()
df['Study ID'] = df['Study ID'].astype(str).str.strip()
df['Group'] = df['Group'].astype(str).str.strip()

# 5. Merge into your master DataFrame (df)
df = df.merge(dichot_subset, on=['Study ID', 'Group'], how='left')

# 6. Create the Binary Target for DCA
# Success (1) = 50% or more remission; Failure (0) = less than 50%
df['binary_outcome'] = (df['Percent Achieved Diagnostic Change'] >= 50).astype(int)

# 7. Fill missing binary outcomes with 0 (assuming failure if not reported as success)
df['binary_outcome'] = df['binary_outcome'].fillna(0).astype(int)

print("Binary target successfully created for Decision Curve Analysis.")
print(df[['Study ID', 'Group', 'Percent Achieved Diagnostic Change', 'binary_outcome']].head())

"""### Feature Engineering (First Attempt)"""

# 1. Normalize baseline severity
# This creates a standardized z-score, allowing for a uniform comparison across
# different diagnostic measures like the CAPS and PCL [2, 3].
df['baseline_z'] = (
    df['baseline_severity'] - df['baseline_severity'].mean()
) / df['baseline_severity'].std()

# 2. Standardize treatment duration column name
# The repository identifies this feature as 'Treatment Duration' [1].
# We use 'duration_fixed' here, which was the standardized name from our merge step.
df['treatment_duration'] = df['duration_fixed']

# 3. Final Check
print("Feature engineering complete.")
print(df[['Study ID', 'baseline_severity', 'baseline_z', 'treatment_duration']].head())

"""### Exploratory Data Analysis (EDA) on First Attempt Features"""

# 1. EDA for baseline_z
print("\nDistribution of baseline_z:")
print(df['baseline_z'].describe())

# 2. EDA for treatment_duration
print("\nDistribution of treatment_duration:")
print(df['treatment_duration'].describe())

# 3. EDA for binary_outcome
print("\nCounts for binary_outcome:")
print(df['binary_outcome'].value_counts())

"""### Debugging Intermediate Columns"""

# Debugging: Inspect intermediate columns to understand the issues

print("\nDistribution of baseline_severity (before z-scoring):")
print(df['baseline_severity'].describe())

print("\nDistribution of duration_fixed (before assigning to treatment_duration):")
print(df['duration_fixed'].describe())

print("\nDistribution of Percent Achieved Diagnostic Change (before creating binary_outcome):")
print(df['Percent Achieved Diagnostic Change'].describe())
print(df['Percent Achieved Diagnostic Change'].value_counts(dropna=False))

"""## Rebuilding Main DataFrame (Arm-Level Correction)

## Rebuilding the Main DataFrame (df) to be Arm-Level

To resolve the persistent merge mismatches, we are restructuring the primary `df` to represent individual intervention arms rather than comparisons between arms.

This involves:
1.  Initializing `df` with arm-level data from `Study_Interventions_20250403`.
2.  Merging study-level characteristics (`features_char`, `features_demo`) into this new arm-level `df`.
3.  Re-integrating arm-level features (`baseline_severity`, `treatment_duration`, `binary_outcome`) which previously failed to merge correctly.

This approach ensures that merge keys (`Study ID`, `Group`) are consistent across all merges, allowing for accurate feature engineering.

### Initialize New Arm-Level DataFrame and Merge Study/Demographic Characteristics
"""

import pandas as pd
import numpy as np

# 1. Initialize a new arm-level dataframe from Study_Interventions_20250403
# This table inherently represents individual intervention arms.
new_df = dataframes['Study_Interventions_20250403'].copy()

# Select the key columns for an arm-level base
new_df = new_df[[
    'Study ID', # This is 'abdallah2022_a' format from Study_Interventions_20250403
    'Intervention Group', # This is 'A' format from Study_Interventions_20250403
    'Standardized Treatment Name',
    'Delivery Method',
    'Treatment Duration'
]].copy()

# Rename the original 'Study ID' to 'arm_id' as it uniquely identifies each arm
new_df.rename(columns={'Study ID': 'arm_id'}, inplace=True)

# Create a new 'Study ID' column by stripping the arm suffix (e.g., 'abdallah2022_a' becomes 'abdallah2022')
# This new 'Study ID' will be used for merging with study-level characteristics (features_char, features_demo)
# and other arm-level data that uses the base study ID.
new_df['Study ID'] = new_df['arm_id'].apply(lambda x: '_'.join(x.split('_')[:-1]) if '_' in x else x)

# Rename 'Intervention Group' to 'Group' for consistency as this is the arm identifier within a study
new_df.rename(columns={'Intervention Group': 'Group'}, inplace=True)

# Clean all string ID columns
new_df['arm_id'] = new_df['arm_id'].astype(str).str.strip().str.lower()
new_df['Study ID'] = new_df['Study ID'].astype(str).str.strip().str.lower()
new_df['Group'] = new_df['Group'].astype(str).str.strip()

# Convert 'Treatment Duration' to numeric and fill NaNs
new_df['Treatment Duration'] = pd.to_numeric(new_df['Treatment Duration'], errors='coerce')
new_df['Treatment Duration'] = new_df['Treatment Duration'].fillna(new_df['Treatment Duration'].median())
new_df.rename(columns={'Treatment Duration': 'treatment_duration'}, inplace=True)

# 2. Re-merge study-level features (features_char, features_demo)
# Ensure merge keys are cleaned consistently for study-level dataframes
features_char_cleaned = features_char.copy()
features_char_cleaned['Study ID'] = features_char_cleaned['Study ID'].astype(str).str.strip().str.lower()

features_demo_cleaned = features_demo.copy()
features_demo_cleaned['Study ID'] = features_demo_cleaned['Study ID'].astype(str).str.strip().str.lower()

# Merge study-level characteristics using the new 'Study ID' column (base study ID)
new_df = new_df.merge(features_char_cleaned, on='Study ID', how='left')
new_df = new_df.merge(features_demo_cleaned, on='Study ID', how='left')

# Ensure all columns are unique at this point before final assignment to df
new_df = new_df.loc[:,~new_df.columns.duplicated()]

# Update the main df reference to this new arm-level dataframe
df = new_df.copy()

print("New arm-level dataframe (df) initialized and study/demo characteristics merged.")
print(df.head())
print("Columns in df after 263a7a0b:", df.columns.tolist())

"""### Re-integrate Baseline Severity and Z-Score"""

# 3. Re-integrate Baseline Severity (adapted from previous Step B)

# Load the source data for baseline severity
baseline_raw = dataframes['PTSD_Continuous_Outcomes_Within_Arms_20250403'].copy()
baseline_raw['Study ID'] = baseline_raw['Study ID'].astype(str).str.strip().str.lower()
baseline_raw['Intervention Group'] = baseline_raw['Intervention Group'].astype(str).str.strip()

# Filter strictly for 'Baseline' scores
baseline_filtered = baseline_raw[baseline_raw['Assessment Point'] == 'Baseline'].copy()
real_median_severity = baseline_filtered['Measure Score Mean'].median()

# Prepare subset for merging
baseline_sub = baseline_filtered[['Study ID', 'Intervention Group', 'Measure Score Mean']].copy()
baseline_sub.columns = ['Study ID', 'Group', 'baseline_severity']

# Drop baseline_severity if it exists in the new df to prevent merge errors
if 'baseline_severity' in df.columns:
    df = df.drop(columns=['baseline_severity'])

# Merge into the new arm-level df
df = df.merge(baseline_sub, on=['Study ID', 'Group'], how='left')
df['baseline_severity'] = df['baseline_severity'].fillna(real_median_severity)

# Recalculate baseline_z with the now varied baseline_severity
df['baseline_z'] = (df['baseline_severity'] - df['baseline_severity'].mean()) / df['baseline_severity'].std()

print("Baseline Severity and Z-Score re-integrated into new arm-level df.")
print(df[['Study ID', 'Group', 'baseline_severity', 'baseline_z']].head())

"""### Re-integrate Binary Outcome (with Debugging)"""

# 4. Re-integrate Binary Outcome (adapted from previous Step C)

# Load the source data for dichotomous outcomes
dichot_within = dataframes['PTSD_Dichotomous_Outcomes_Within_Arms_20250403'].copy()
dichot_within['Study ID'] = dichot_within['Study ID'].astype(str).str.strip().str.lower()
dichot_within['Intervention Group'] = dichot_within['Intervention Group'].astype(str).str.strip()

# Filter for End of Treatment (Assessment Point '0') and primary diagnostic change
dichot_filtered = dichot_within[(
dichot_within['Assessment Point'] == '0') &
                                (dichot_within['Diagnostic Change Definition Number'] == 1)
                               ].copy()

dichot_sub = dichot_filtered[['Study ID', 'Intervention Group', 'Percent Achieved Diagnostic Change']].copy()
dichot_sub.columns = ['Study ID', 'Group', 'Percent Achieved Diagnostic Change']

# --- Debugging added: Check merge keys ---
print("\n--- Debugging Dichotomous Outcome Merge ---")
print(f"Unique (Study ID, Group) pairs in df: {df[['Study ID', 'Group']].drop_duplicates().shape[0]}")
print(f"Unique (Study ID, Group) pairs in dichot_sub: {dichot_sub[['Study ID', 'Group']].drop_duplicates().shape[0]}")

# Temporarily perform an inner merge to see how many rows would actually match
matched_dichot_rows = pd.merge(df[['Study ID', 'Group']].drop_duplicates(), dichot_sub[['Study ID', 'Group']].drop_duplicates(), on=['Study ID', 'Group'], how='inner')
print(f"Number of (Study ID, Group) pairs that would match in an inner join: {matched_dichot_rows.shape[0]}")
print("-------------------------------------------")
# --- End Debugging ---

# Drop existing columns if they exist to prevent merge errors
if 'Percent Achieved Diagnostic Change' in df.columns:
    df = df.drop(columns=['Percent Achieved Diagnostic Change'])
if 'binary_outcome' in df.columns:
    df = df.drop(columns=['binary_outcome'])

# Merge into the new arm-level df
df = df.merge(dichot_sub, on=['Study ID', 'Group'], how='left')

# Set the binary outcome with a 30% threshold
df['binary_outcome'] = (df['Percent Achieved Diagnostic Change'] >= 30).astype(int)

# Fill any remaining NaNs in binary_outcome with 0 (for arms that didn't have this metric)
df['binary_outcome'] = df['binary_outcome'].fillna(0).astype(int)

print(f"Binary Target re-integrated into new arm-level df. Success cases (1.0) at 30% threshold: {df['binary_outcome'].sum()}")
print(df[['Study ID', 'Group', 'Percent Achieved Diagnostic Change', 'binary_outcome']].head())

"""### Final EDA on Restructured Arm-Level DataFrame (after initial correction)"""

# 5. Final EDA on the restructured arm-level df

print("\n--- Final EDA on Restructured Arm-Level DataFrame ---")

# Distribution of baseline_z
print("\nDistribution of baseline_z:")
print(df['baseline_z'].describe())

# Distribution of treatment_duration
print("\nDistribution of treatment_duration:")
print(df['treatment_duration'].describe())

# Counts for binary_outcome
print("\nCounts for binary_outcome:")
print(df['binary_outcome'].value_counts())

"""### Re-integrate Binary Outcome (Second Debugging Pass)"""

# 4. Re-integrate Binary Outcome (adapted from previous Step C)

# Load the source data for dichotomous outcomes
dichot_within = dataframes['PTSD_Dichotomous_Outcomes_Within_Arms_20250403'].copy()
dichot_within['Study ID'] = dichot_within['Study ID'].astype(str).str.strip().str.lower()
dichot_within['Intervention Group'] = dichot_within['Intervention Group'].astype(str).str.strip()

# Filter for End of Treatment (Assessment Point '0') and primary diagnostic change
dichot_filtered = dichot_within[(
dichot_within['Assessment Point'] == '0') &
                                (dichot_within['Diagnostic Change Definition Number'] == 1)
                               ].copy()

dichot_sub = dichot_filtered[['Study ID', 'Intervention Group', 'Percent Achieved Diagnostic Change']].copy()
dichot_sub.columns = ['Study ID', 'Group', 'Percent Achieved Diagnostic Change']

# Drop existing columns if they exist to prevent merge errors
if 'Percent Achieved Diagnostic Change' in df.columns:
    df = df.drop(columns=['Percent Achieved Diagnostic Change'])
if 'binary_outcome' in df.columns:
    df = df.drop(columns=['binary_outcome'])

# Merge into the new arm-level df
df = df.merge(dichot_sub, on=['Study ID', 'Group'], how='left')

# Set the binary outcome with a 30% threshold
df['binary_outcome'] = (df['Percent Achieved Diagnostic Change'] >= 30).astype(int)

# Fill any remaining NaNs in binary_outcome with 0 (for arms that didn't have this metric)
df['binary_outcome'] = df['binary_outcome'].fillna(0).astype(int)

print(f"Binary Target re-integrated into new arm-level df. Success cases (1.0) at 30% threshold: {df['binary_outcome'].sum()}")
print(df[['Study ID', 'Group', 'Percent Achieved Diagnostic Change', 'binary_outcome']].head())

"""### Re-integrate Binary Outcome (Third Debugging Pass)"""

# 4. Re-integrate Binary Outcome (adapted from previous Step C)

# Load the source data for dichotomous outcomes
dichot_within = dataframes['PTSD_Dichotomous_Outcomes_Within_Arms_20250403'].copy()
dichot_within['Study ID'] = dichot_within['Study ID'].astype(str).str.strip().str.lower()
dichot_within['Intervention Group'] = dichot_within['Intervention Group'].astype(str).str.strip()

# Filter for End of Treatment (Assessment Point '0') and primary diagnostic change
dichot_filtered = dichot_within[(
dichot_within['Assessment Point'] == '0') &
                                (dichot_within['Diagnostic Change Definition Number'] == 1)
                               ].copy()

dichot_sub = dichot_filtered[['Study ID', 'Intervention Group', 'Percent Achieved Diagnostic Change']].copy()
dichot_sub.columns = ['Study ID', 'Group', 'Percent Achieved Diagnostic Change']

# --- Debugging added: Check merge keys ---
print("\n--- Debugging Dichotomous Outcome Merge ---")
print(f"Unique (Study ID, Group) pairs in df: {df[['Study ID', 'Group']].drop_duplicates().shape[0]}")
print(f"Unique (Study ID, Group) pairs in dichot_sub: {dichot_sub[['Study ID', 'Group']].drop_duplicates().shape[0]}")

# Temporarily perform an inner merge to see how many rows would actually match
matched_dichot_rows = pd.merge(df[['Study ID', 'Group']].drop_duplicates(), dichot_sub[['Study ID', 'Group']].drop_duplicates(), on=['Study ID', 'Group'], how='inner')
print(f"Number of (Study ID, Group) pairs that would match in an inner join: {matched_dichot_rows.shape[0]}")
print("-------------------------------------------")
# --- End Debugging ---

# Drop existing columns if they exist to prevent merge errors
if 'Percent Achieved Diagnostic Change' in df.columns:
    df = df.drop(columns=['Percent Achieved Diagnostic Change'])
if 'binary_outcome' in df.columns:
    df = df.drop(columns=['binary_outcome'])

# Merge into the new arm-level df
df = df.merge(dichot_sub, on=['Study ID', 'Group'], how='left')

# Set the binary outcome with a 30% threshold
df['binary_outcome'] = (df['Percent Achieved Diagnostic Change'] >= 30).astype(int)

# Fill any remaining NaNs in binary_outcome with 0 (for arms that didn't have this metric)
df['binary_outcome'] = df['binary_outcome'].fillna(0).astype(int)

print(f"Binary Target re-integrated into new arm-level df. Success cases (1.0) at 30% threshold: {df['binary_outcome'].sum()}")
print(df[['Study ID', 'Group', 'Percent Achieved Diagnostic Change', 'binary_outcome']].head())

"""### Final EDA on Restructured Arm-Level DataFrame (after second debugging pass)"""

# 5. Final EDA on the restructured arm-level df

print("\n--- Final EDA on Restructured Arm-Level DataFrame ---")

# Distribution of baseline_z
print("\nDistribution of baseline_z:")
print(df['baseline_z'].describe())

# Distribution of treatment_duration
print("\nDistribution of treatment_duration:")
print(df['treatment_duration'].describe())

# Counts for binary_outcome
print("\nCounts for binary_outcome:")
print(df['binary_outcome'].value_counts())

"""### Re-integrate Baseline Severity (Fourth Debugging Pass)"""

# 3. Re-integrate Baseline Severity (adapted from previous Step B)

# Load the source data for baseline severity
baseline_raw = dataframes['PTSD_Continuous_Outcomes_Within_Arms_20250403'].copy()
baseline_raw['Study ID'] = baseline_raw['Study ID'].astype(str).str.strip().str.lower()
baseline_raw['Intervention Group'] = baseline_raw['Intervention Group'].astype(str).str.strip()

# Filter strictly for 'Baseline' scores
baseline_filtered = baseline_raw[baseline_raw['Assessment Point'] == 'Baseline'].copy()
real_median_severity = baseline_filtered['Measure Score Mean'].median()

# Prepare subset for merging
baseline_sub = baseline_filtered[['Study ID', 'Intervention Group', 'Measure Score Mean']].copy()
baseline_sub.columns = ['Study ID', 'Group', 'baseline_severity']

# Drop baseline_severity if it exists in the new df to prevent merge errors
if 'baseline_severity' in df.columns:
    df = df.drop(columns=['baseline_severity'])

# Merge into the new arm-level df
df = df.merge(baseline_sub, on=['Study ID', 'Group'], how='left')
df['baseline_severity'] = df['baseline_severity'].fillna(real_median_severity)

# Recalculate baseline_z with the now varied baseline_severity
df['baseline_z'] = (df['baseline_severity'] - df['baseline_severity'].mean()) / df['baseline_severity'].std()

print("Baseline Severity and Z-Score re-integrated into new arm-level df.")
print(df[['Study ID', 'Group', 'baseline_severity', 'baseline_z']].head())

"""### Re-integrate Binary Outcome (Fourth Debugging Pass)"""

# 4. Re-integrate Binary Outcome (adapted from previous Step C)

# Load the source data for dichotomous outcomes
dichot_within = dataframes['PTSD_Dichotomous_Outcomes_Within_Arms_20250403'].copy()
dichot_within['Study ID'] = dichot_within['Study ID'].astype(str).str.strip().str.lower()
dichot_within['Intervention Group'] = dichot_within['Intervention Group'].astype(str).str.strip()

# Filter for End of Treatment (Assessment Point '0') and primary diagnostic change
dichot_filtered = dichot_within[(
dichot_within['Assessment Point'] == '0') &
                                (dichot_within['Diagnostic Change Definition Number'] == 1)
                               ].copy()

dichot_sub = dichot_filtered[['Study ID', 'Intervention Group', 'Percent Achieved Diagnostic Change']].copy()
dichot_sub.columns = ['Study ID', 'Group', 'Percent Achieved Diagnostic Change']

# --- Debugging added: Check merge keys ---
print("\n--- Debugging Dichotomous Outcome Merge ---")
print(f"Unique (Study ID, Group) pairs in df: {df[['Study ID', 'Group']].drop_duplicates().shape[0]}")
print(f"Unique (Study ID, Group) pairs in dichot_sub: {dichot_sub[['Study ID', 'Group']].drop_duplicates().shape[0]}")

# Temporarily perform an inner merge to see how many rows would actually match
matched_dichot_rows = pd.merge(df[['Study ID', 'Group']].drop_duplicates(), dichot_sub[['Study ID', 'Group']].drop_duplicates(), on=['Study ID', 'Group'], how='inner')
print(f"Number of (Study ID, Group) pairs that would match in an inner join: {matched_dichot_rows.shape[0]}")

# Print unique combinations to identify discrepancies
print("\nUnique (Study ID, Group) in df (sample):")
print(df[['Study ID', 'Group']].drop_duplicates().head(20))
print("\nUnique (Study ID, Group) in dichot_sub (sample):")
print(dichot_sub[['Study ID', 'Group']].drop_duplicates().head(20))

print("-------------------------------------------")
# --- End Debugging ---

# Drop existing columns if they exist to prevent merge errors
if 'Percent Achieved Diagnostic Change' in df.columns:
    df = df.drop(columns=['Percent Achieved Diagnostic Change'])
if 'binary_outcome' in df.columns:
    df = df.drop(columns=['binary_outcome'])

# Merge into the new arm-level df
df = df.merge(dichot_sub, on=['Study ID', 'Group'], how='left')

# Set the binary outcome with a 30% threshold
df['binary_outcome'] = (df['Percent Achieved Diagnostic Change'] >= 30).astype(int)

# Fill any remaining NaNs in binary_outcome with 0 (for arms that didn't have this metric)
df['binary_outcome'] = df['binary_outcome'].fillna(0).astype(int)

print(f"Binary Target re-integrated into new arm-level df. Success cases (1.0) at 30% threshold: {df['binary_outcome'].sum()}")
print(df[['Study ID', 'Group', 'Percent Achieved Diagnostic Change', 'binary_outcome']].head())

"""### Final EDA on Restructured Arm-Level DataFrame (after fourth debugging pass)"""

# 5. Final EDA on the restructured arm-level df

print("\n--- Final EDA on Restructured Arm-Level DataFrame ---")

# Distribution of baseline_z
print("\nDistribution of baseline_z:")
print(df['baseline_z'].describe())

# Distribution of treatment_duration
print("\nDistribution of treatment_duration:")
print(df['treatment_duration'].describe())

# Counts for binary_outcome
print("\nCounts for binary_outcome:")
print(df['binary_outcome'].value_counts())

"""### Re-integrate Baseline Severity (Fifth Debugging Pass)"""

# 3. Re-integrate Baseline Severity (adapted from previous Step B)

# Load the source data for baseline severity
baseline_raw = dataframes['PTSD_Continuous_Outcomes_Within_Arms_20250403'].copy()
baseline_raw['Study ID'] = baseline_raw['Study ID'].astype(str).str.strip().str.lower()
baseline_raw['Intervention Group'] = baseline_raw['Intervention Group'].astype(str).str.strip()

# Filter strictly for 'Baseline' scores
baseline_filtered = baseline_raw[baseline_raw['Assessment Point'] == 'Baseline'].copy()
real_median_severity = baseline_filtered['Measure Score Mean'].median()

# Prepare subset for merging
baseline_sub = baseline_filtered[['Study ID', 'Intervention Group', 'Measure Score Mean']].copy()
baseline_sub.columns = ['Study ID', 'Group', 'baseline_severity']

# Drop baseline_severity if it exists in the new df to prevent merge errors
if 'baseline_severity' in df.columns:
    df = df.drop(columns=['baseline_severity'])

# Merge into the new arm-level df
df = df.merge(baseline_sub, on=['Study ID', 'Group'], how='left')
df['baseline_severity'] = df['baseline_severity'].fillna(real_median_severity)

# Recalculate baseline_z with the now varied baseline_severity
df['baseline_z'] = (df['baseline_severity'] - df['baseline_severity'].mean()) / df['baseline_severity'].std()

print("Baseline Severity and Z-Score re-integrated into new arm-level df.")
print(df[['Study ID', 'Group', 'baseline_severity', 'baseline_z']].head())

"""### Re-integrate Binary Outcome (Fifth Debugging Pass)"""

# 4. Re-integrate Binary Outcome (adapted from previous Step C)

# Load the source data for dichotomous outcomes
dichot_within = dataframes['PTSD_Dichotomous_Outcomes_Within_Arms_20250403'].copy()
dichot_within['Study ID'] = dichot_within['Study ID'].astype(str).str.strip().str.lower()
dichot_within['Intervention Group'] = dichot_within['Intervention Group'].astype(str).str.strip()

# Filter for End of Treatment (Assessment Point '0') and primary diagnostic change
dichot_filtered = dichot_within[(
dichot_within['Assessment Point'] == '0') &
                                (dichot_within['Diagnostic Change Definition Number'] == 1)
                               ].copy()

dichot_sub = dichot_filtered[['Study ID', 'Intervention Group', 'Percent Achieved Diagnostic Change']].copy()
dichot_sub.columns = ['Study ID', 'Group', 'Percent Achieved Diagnostic Change']

# Drop existing columns if they exist to prevent merge errors
if 'Percent Achieved Diagnostic Change' in df.columns:
    df = df.drop(columns=['Percent Achieved Diagnostic Change'])
if 'binary_outcome' in df.columns:
    df = df.drop(columns=['binary_outcome'])

# Merge into the new arm-level df
df = df.merge(dichot_sub, on=['Study ID', 'Group'], how='left')

# Set the binary outcome with a 30% threshold
df['binary_outcome'] = (df['Percent Achieved Diagnostic Change'] >= 30).astype(int)

# Fill any remaining NaNs in binary_outcome with 0 (for arms that didn't have this metric)
df['binary_outcome'] = df['binary_outcome'].fillna(0).astype(int)

print(f"Binary Target re-integrated into new arm-level df. Success cases (1.0) at 30% threshold: {df['binary_outcome'].sum()}")
print(df[['Study ID', 'Group', 'Percent Achieved Diagnostic Change', 'binary_outcome']].head())

"""### Final EDA on Restructured Arm-Level DataFrame (after fifth debugging pass)"""

# 5. Final EDA on the restructured arm-level df

print("\n--- Final EDA on Restructured Arm-Level DataFrame ---")

# Distribution of baseline_z
print("\nDistribution of baseline_z:")
print(df['baseline_z'].describe())

# Distribution of treatment_duration
print("\nDistribution of treatment_duration:")
print(df['treatment_duration'].describe())

# Counts for binary_outcome
print("\nCounts for binary_outcome:")
print(df['binary_outcome'].value_counts())

"""## Corrected Data Assembly Steps

### Corrected Merge Keys and Treatment Duration
"""

import pandas as pd
import numpy as np

# 1. Clean Master DF keys (ensure consistency for future merges)
df['Study ID'] = df['Study ID'].astype(str).str.strip().str.lower()
df['Group'] = df['Group'].astype(str).str.strip()

# 2. Fix Treatment Duration
# Use the already loaded dataframe from the dataframes dictionary
interventions = dataframes['Study_Interventions_20250403'].copy()
interventions['Study ID'] = interventions['Study ID'].astype(str).str.strip().str.lower()
interventions['Group'] = interventions['Intervention Group'].astype(str).str.strip()

# IMPORTANT FIX: Extract the base Study ID from interventions to match the main df's Study ID
interventions['base_study_id'] = interventions['Study ID'].apply(lambda x: '_'.join(x.split('_')[:-1]) if '_' in x else x)

# Select 'Treatment Duration' (the correct source name) using the new 'base_study_id'
duration_sub = interventions[['base_study_id', 'Group', 'Treatment Duration']].copy()
duration_sub.columns = ['Study ID', 'Group', 'treatment_duration']
duration_sub['treatment_duration'] = pd.to_numeric(duration_sub['treatment_duration'], errors='coerce')

# Drop treatment_duration from df if it exists to avoid merge conflicts and ensure a clean re-merge
if 'treatment_duration' in df.columns:
    df = df.drop(columns=['treatment_duration'])

# Merge using the corrected 'Study ID'
df = df.merge(duration_sub, on=['Study ID', 'Group'], how='left')

# Fill remaining NaNs. Use the global median of the original 'duration_sub' if the column is still all NaNs
# This ensures a value is used even if the merge completely failed for some reason.
global_median_duration = duration_sub['treatment_duration'].median()
df['treatment_duration'] = df['treatment_duration'].fillna(global_median_duration)

print("Step A: Corrected Merge Keys and Treatment Duration complete.")

"""### Corrected Baseline Severity and Z-Score"""

# 1. Fix Baseline Severity and Z-Score
# Use the already loaded dataframe from the dataframes dictionary
baseline_raw = dataframes['PTSD_Continuous_Outcomes_Within_Arms_20250403'].copy()
baseline_raw['Study ID'] = baseline_raw['Study ID'].astype(str).str.strip().str.lower()
baseline_raw['Group'] = baseline_raw['Intervention Group'].astype(str).str.strip()

# Filter strictly for Baseline and calculate a real median from the source
baseline_filtered = baseline_raw[baseline_raw['Assessment Point'] == 'Baseline'].copy()
real_median_severity = baseline_filtered['Measure Score Mean'].median()

baseline_sub = baseline_filtered[['Study ID', 'Group', 'Measure Score Mean']].copy()
baseline_sub.columns = ['Study ID', 'Group', 'baseline_severity']

# Drop baseline_severity from df if it exists to avoid MergeError
if 'baseline_severity' in df.columns:
    df = df.drop(columns=['baseline_severity'])

# Merge and Re-Calculate Z-Score
df = df.merge(baseline_sub, on=['Study ID', 'Group'], how='left')
df['baseline_severity'] = df['baseline_severity'].fillna(real_median_severity)

# Now Z-score will have a standard deviation because baseline_severity has variation
df['baseline_z'] = (df['baseline_severity'] - df['baseline_severity'].mean()) / df['baseline_severity'].std()

print("Step B: Corrected Baseline Severity and Z-Score complete.")

"""### Step C: Adjusted Binary Target Threshold"""

# 1. Load Outcome Data
# Use the already loaded dataframe from the dataframes dictionary
dichot_within = dataframes['PTSD_Dichotomous_Outcomes_Within_Arms_20250403'].copy()
dichot_within['Study ID'] = dichot_within['Study ID'].astype(str).str.strip().str.lower()
dichot_within['Group'] = dichot_within['Intervention Group'].astype(str).str.strip()

# 2. Filter for End of Treatment (Assessment Point 0)
dichot_filtered = dichot_within[(dichot_within['Assessment Point'] == '0') &
                                (dichot_within['Diagnostic Change Definition Number'] == 1)].copy()

dichot_sub = dichot_filtered[['Study ID', 'Group', 'Percent Achieved Diagnostic Change']].copy()

# Drop 'Percent Achieved Diagnostic Change' and 'binary_outcome' if they exist to avoid MergeError
if 'Percent Achieved Diagnostic Change' in df.columns:
    df = df.drop(columns=['Percent Achieved Diagnostic Change'])
if 'binary_outcome' in df.columns:
    df = df.drop(columns=['binary_outcome'])

# 3. Merge and Set a Clinical Threshold of 50%
df = df.merge(dichot_sub, on=['Study ID', 'Group'], how='left')

# Use 50% as the new threshold for success
df['binary_outcome'] = (df['Percent Achieved Diagnostic Change'] >= 50).astype(int)

print(f"Step C: Adjusted Binary Target Threshold complete. Success cases (1.0) at 50% threshold: {df['binary_outcome'].sum()}")

"""### Verify Binary Outcome Counts"""

print("Updated counts for binary_outcome with 50% threshold:")
print(df['binary_outcome'].value_counts())

"""### Check DataFrame Shape"""

print(df.shape)

"""### Reapply Veteran Filter"""

# Reapply the veteran filter to the current arm-level df
original_rows = df.shape[0]
df = df[
    (df['Veteran Percent'] > 0) |
    (df['Military Status'] == 'Veteran')
]
filtered_rows = df.shape[0]

print(f"Veteran filter reapplied. Original rows: {original_rows}, Filtered rows: {filtered_rows}")
print(f"Rows removed: {original_rows - filtered_rows}")
print("Current shape of df after re-applying veteran filter:", df.shape)

"""### One-Hot Encode Categorical Features"""

df = pd.get_dummies(df, columns=[
    'Trauma Type',
    'Delivery Method',
    'Standardized Treatment Name'
])

"""### Impute Missing Numerical Values"""

from sklearn.impute import SimpleImputer

num_cols = df.select_dtypes(include=np.number).columns

imputer = SimpleImputer(strategy='median')
df[num_cols] = imputer.fit_transform(df[num_cols])

"""### Final Data Checks (Shape, Target Balance, Missing Values)"""

print("Shape:", df.shape)

print("\nTarget balance:")
print(df['binary_outcome'].value_counts())

print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False).head(10))

"""### Reapplying Veteran Filter (Duplicate Check - can be removed if intentional)"""

df = df[
    (df['Veteran Percent'] > 0) |
    (df['Military Status'] == 'Veteran')
]

"""### Final Data Checks (After Duplicate Filter - can be removed if intentional)"""

print("Shape:", df.shape)

print("\nTarget balance:")
print(df['binary_outcome'].value_counts())

print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False).head(10))

"""### Export Final DataFrame (First Save)"""

output_path = data_path + 'Final_Veterans_PTSD_Dataset.csv'
df.to_csv(output_path, index=False)

print("Saved to:", output_path)

"""### Export Final DataFrame (Second Save - for reproducibility)"""

output_path_final = data_path + 'Final_Veterans_PTSD_Dataset_2.csv'
df.to_csv(output_path_final, index=False)

print(f"Final DataFrame saved to: {output_path_final}")

"""### Load and Verify Saved DataFrame"""

import pandas as pd

# Load the saved CSV file
output_path = data_path + 'Final_Veterans_PTSD_Dataset.csv'
loaded_df = pd.read_csv(output_path)

# Print all columns of the loaded DataFrame
print("Columns in the loaded CSV file:")
print(loaded_df.columns.tolist())

# Display the first few rows to confirm content
print("\nFirst 5 rows of the loaded DataFrame:")
display(loaded_df.head())

"""### Display Current DataFrame Columns and Head"""

print("All columns in the DataFrame:")
print(df.columns.tolist())

print("\nFirst 5 rows of the DataFrame (showing one-hot encoded columns):")
display(df.head())

"""## 4.2.1 Final Dataset Overview"""

# ==========================
# FINAL DATASET OVERVIEW
# ==========================

n_observations = df.shape[0]
n_variables = df.shape[1]

print("Number of observations:", n_observations)
print("Number of variables:", n_variables)

"""### Step 1: Create Table 4.1 Automatically

### Step 2: Create Table 4.1 Automatically
"""

# ==========================
# TABLE 4.1
# FINAL DATASET OVERVIEW
# ==========================

table_4_1 = pd.DataFrame({
    'Characteristic': [
        'Number of observations',
        'Number of predictors',
        'Outcome variable',
        'Success threshold',
        'Missing data strategy'
    ],
    'Value': [
        df.shape[0],
        df.shape[1]-1,  # minus outcome variable
        'Binary Outcome',
        '≥50% diagnostic change',
        'Median imputation'
    ]
})

display(table_4_1)

"""### Step 2: Export Table to Excel

### Step 3: Export Table to Excel
"""

table_4_1.to_excel(
    "Table_4_1_Final_Dataset_Overview.xlsx",
    index=False
)

print("Table exported successfully.")

"""### Step 3: Missing Data Summary

### Step 4: Missing Data Summary
"""

# ==========================
# MISSING DATA CHECK
# ==========================

missing_summary = df.isnull().sum()

print("Total Missing Values:")
print(missing_summary.sum())

print("\nVariables with Missing Values:")
print(missing_summary[missing_summary > 0])

"""### Step 4: Dataset Suitability Statistics

### Check Column Names
"""

print("Confirming exact column names in the DataFrame:")
print(df.columns.tolist())

"""### Create the Continuous Variables List"""

# Define the list of continuous variables based on your dataset and previous requests.
# Added 'Male Percent' and 'Percent Achieved Diagnostic Change' as discussed.
continuous_vars = [
    'Veteran Percent',
    'Female Percent',
    'Male Percent',
    'baseline_severity',
    'baseline_z',
    'treatment_duration',
    'Percent Achieved Diagnostic Change'
]

# Filter out any variables that might not exist in the current df, for robustness
continuous_vars = [col for col in continuous_vars if col in df.columns]

print(f"\nContinuous variables selected: {continuous_vars}")

"""### Generate Descriptive Statistics"""

# =====================================
# DESCRIPTIVE STATISTICS
# =====================================

desc_stats = df[continuous_vars].describe().T
display(desc_stats)

"""### Create Dissertation Table 4.2"""

# =====================================
# TABLE 4.2
# DESCRIPTIVE STATISTICS
# =====================================

table_4_2 = pd.DataFrame({
    'Variable': desc_stats.index,
    'Mean': desc_stats['mean'].round(2),
    'SD': desc_stats['std'].round(2),
    'Min': desc_stats['min'].round(2),
    'Max': desc_stats['max'].round(2)
})

display(table_4_2)

"""Export Table for Word"""

table_4_2.to_excel(
    "Table_4_2_Descriptive_Statistics.xlsx",
    index=False
)

print("\nTable 4.2 exported successfully to 'Table_4_2_Descriptive_Statistics.xlsx'.")

"""### Additional Analysis: Generate Histograms for Continuous Variables

### Overall Dataset Suitability Check
"""

import matplotlib.pyplot as plt
import seaborn as sns
import os

# Ensure the output directory exists
output_image_dir = os.path.join(data_path, 'histograms')
os.makedirs(output_image_dir, exist_ok=True)

for col in continuous_vars:
    plt.figure(figsize=(8,5))
    sns.histplot(df[col].dropna(), bins=30, kde=True, edgecolor='black') # Using seaborn for better aesthetics and KDE
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.grid(axis='y', alpha=0.75)

    # Save the figure
    image_filename = f"distribution_of_{col.replace(' ', '_').replace('%', 'percent')}.png"
    image_filepath = os.path.join(output_image_dir, image_filename)
    plt.savefig(image_filepath, bbox_inches='tight')
    print(f"Histogram for '{col}' saved to: {image_filepath}")

    plt.show()

# ==========================
# DATASET SUITABILITY
# ==========================

print("Observations:", df.shape[0])
print("Variables:", df.shape[1])

print("\nOutcome Distribution:")
print(df['binary_outcome'].value_counts())

print("\nOutcome Percentage:")
print(
    round(
        df['binary_outcome'].value_counts(normalize=True)*100,
        2
    )
)

"""### Calculate Skewness and Kurtosis"""



from scipy.stats import skew, kurtosis

distribution_stats = pd.DataFrame({
    'Variable': continuous_vars,
    'Skewness': [round(skew(df[var].dropna()), 3) for var in continuous_vars],
    'Kurtosis': [round(kurtosis(df[var].dropna()), 3) for var in continuous_vars]
})
display(distribution_stats)

"""Create Dissertation Table 4.2a"""

table_4_2a = distribution_stats.copy()
display(table_4_2a)

"""### Export Table to Excel

### Step 3: Export Table to Excel
"""

table_4_2a.to_excel(
    "Table_4_2a_Distribution_Assessment.xlsx",
    index=False
)

print("Table exported successfully.")

"""### Outcome Frequency Table

## 4.2.3 Distribution of Treatment Success

This section assesses the distribution of the `binary_outcome` variable, which is crucial for understanding class imbalance in the dataset.

### Step 1: Outcome Frequency Table
"""

outcome_counts = (
    df['binary_outcome']
    .value_counts()
    .sort_index()
)

outcome_percentages = (
    df['binary_outcome']
    .value_counts(normalize=True)
    .sort_index() * 100
)

table_4_3 = pd.DataFrame({
    'Outcome': ['Failure (0)', 'Success (1)'],
    'Frequency': outcome_counts.values,
    'Percentage': outcome_percentages.round(2).values
})

display(table_4_3)

"""### Generate Figure 4.1 (Outcome Distribution Bar Plot)"""

table_4_3.to_excel(
    "Table_4_3_Outcome_Distribution.xlsx",
    index=False
)
print("Table 4.3 exported successfully to 'Table_4_3_Outcome_Distribution.xlsx'.")

"""### Generate Figure 4.1"""

import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))

df['binary_outcome'].value_counts().sort_index().plot(
    kind='bar',
    color=['skyblue', 'lightcoral'] # Added colors for better visualization
)

plt.title('Distribution of Treatment Outcomes')
plt.xlabel('Outcome')
plt.ylabel('Frequency')

plt.xticks(
    [0,1],
    ['Failure (0)', 'Success (1)'],
    rotation=0
)

plt.tight_layout()

plt.savefig(
    'Figure_4_1_Outcome_Distribution.png',
    dpi=300,
    bbox_inches='tight'
)

print("Figure 4.1 saved to 'Figure_4_1_Outcome_Distribution.png'.")
plt.show()

"""## 4.3 Logistic Regression Model Development"""

for col in df.columns:
    print(col)

"""### One-Hot Encode Remaining Categorical Features"""

df = pd.get_dummies(df, columns=['Diagnostic Measure', 'Clinical Setting', 'Military Status', 'Group'])

"""### Verify Columns After One-Hot Encoding"""

print('Columns after one-hot encoding:')
print(df.columns.tolist())
print(f'New shape: {df.shape}')

"""### Define Features (X) and Target (y) for Logistic Regression"""



y = df['binary_outcome']

X = df.drop(columns=[
    'arm_id',
    'Study ID',
    'binary_outcome',
    'Percent Achieved Diagnostic Change',
    'Male Percent',
    'baseline_severity'
])

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nTarget variable (y) value counts:")
print(y.value_counts())

"""### Verify Data Types of Features"""

print(X.dtypes.value_counts())

"""### Check for Missing Values in Features"""

print("Missing values:", X.isnull().sum().sum())

"""### Verify Data Types and Missing Values (Redundant Check)"""

print(X.dtypes.value_counts())
print("Missing values:", X.isnull().sum().sum())

"""### Summarize Predictor Categories"""

predictor_summary = {
    "Veteran Percent": sum(col == "Veteran Percent" for col in X.columns),
    "Female Percent": sum(col == "Female Percent" for col in X.columns),
    "baseline_z": sum(col == "baseline_z" for col in X.columns),
    "treatment_duration": sum(col == "treatment_duration" for col in X.columns),

    "Trauma Type": sum(col.startswith("Trauma Type_") for col in X.columns),
    "Delivery Method": sum(col.startswith("Delivery Method_") for col in X.columns),
    "Treatment Name": sum(col.startswith("Standardized Treatment Name_") for col in X.columns),
    "Diagnostic Measure": sum(col.startswith("Diagnostic Measure_") for col in X.columns),
    "Clinical Setting": sum(col.startswith("Clinical Setting_") for col in X.columns),
    "Military Status": sum(col.startswith("Military Status_") for col in X.columns),
    "Group": sum(col.startswith("Group_") for col in X.columns)
}

for k, v in predictor_summary.items():
    print(f"{k}: {v}")

"""### Split Data into Training and Testing Sets"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

print("\nTraining outcomes:")
print(y_train.value_counts())

print("\nTesting outcomes:")
print(y_test.value_counts())

"""### Verify Stratification in Train/Test Split"""

print("Full Dataset")
print(round(y.value_counts(normalize=True) * 100, 2))

print("\nTraining Dataset")
print(round(y_train.value_counts(normalize=True) * 100, 2))

print("\nTesting Dataset")
print(round(y_test.value_counts(normalize=True) * 100, 2))

"""### Initialize Logistic Regression Model with Class Weights"""

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression(
    class_weight='balanced',
    max_iter=5000,
    random_state=42
)

"""### Calculate Class Weights Manually (for verification)"""

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

for cls, weight in zip(classes, weights):
    print(f"Class {int(cls)} weight: {weight:.4f}")

"""### Train Logistic Regression Model"""

log_reg.fit(X_train, y_train)

print("Logistic Regression model trained successfully.")

"""## 4.3.1 Model Evaluation"""

y_pred = log_reg.predict(X_test)

y_pred_proba = log_reg.predict_proba(X_test)[:,1]

"""### Calculate Evaluation Metrics"""

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
import pandas as pd

accuracy = round(accuracy_score(y_test, y_pred),4)
precision = round(precision_score(y_test, y_pred),4)
recall = round(recall_score(y_test, y_pred),4)
f1 = round(f1_score(y_test, y_pred),4)
roc_auc = round(roc_auc_score(y_test, y_pred_proba),4)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)
print("ROC-AUC:", roc_auc)

# Create a DataFrame for the metrics
metrics_df = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC-AUC'],
    'Value': [accuracy, precision, recall, f1, roc_auc]
})

# Export to Excel
metrics_df.to_excel("Table_4_5_Model_Performance_Metrics.xlsx", index=False)

print("\nModel performance metrics exported successfully to 'Table_4_5_Model_Performance_Metrics.xlsx'.")

"""### Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)

print(cm)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm
)

disp.plot()

plt.title("Confusion Matrix - Logistic Regression")
plt.show()

"""### ROC Curve"""

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

fpr, tpr, thresholds = roc_curve(
    y_test,
    y_pred_proba
)

roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8,6))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
plt.plot([0,1],[0,1],'--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Logistic Regression")
plt.legend()

plt.show()

"""### Classification Report"""

from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        y_pred
    )
)

"""## 4.3.2 Model Interpretation"""

import pandas as pd
import numpy as np

coef_df = pd.DataFrame({
    'Predictor': X_train.columns,
    'Coefficient': log_reg.coef_[0]
})

coef_df['Odds_Ratio'] = np.exp(coef_df['Coefficient'])

coef_df = coef_df.sort_values(
    by='Coefficient',
    ascending=False
)

print("Top 20 Predictors by Coefficient (and Odds Ratio):")
display(coef_df.head(20))

"""### Top 20 Predictors by Coefficient and Odds Ratio"""

print("15 Strongest Positive Predictors (highest coefficients):")
display(coef_df.sort_values(
    by='Coefficient',
    ascending=False
).head(15))

"""### 15 Strongest Positive Predictors"""

print("15 Strongest Negative Predictors (lowest coefficients):")
display(coef_df.sort_values(
    by='Coefficient',
    ascending=True
).head(15))

"""### 15 Strongest Negative Predictors"""

import statsmodels.api as sm

# 1. Define the list of corrected reduced predictors
# Exclude 'Trauma Type_MST' and 'Trauma Type_Other'

# Start with continuous variables
reduced_predictors_corrected = [
    'Veteran Percent',
    'Female Percent',
    'baseline_z',
    'treatment_duration'
]

# Add 'Trauma Type_' columns, excluding the problematic ones
trauma_type_cols_corrected = [
    col for col in X_train.columns if col.startswith('Trauma Type_')
    and col not in ['Trauma Type_MST', 'Trauma Type_Other']
]
reduced_predictors_corrected.extend(trauma_type_cols_corrected)

# 2. Create the new DataFrame X_train_reduced_corrected
X_train_reduced_corrected = X_train[reduced_predictors_corrected].copy()

# 3. Add a constant to X_train_reduced_corrected for statsmodels
X_train_reduced_sm_corrected = sm.add_constant(X_train_reduced_corrected)

print("Corrected reduced predictors defined:")
print(reduced_predictors_corrected)
print("Shape of X_train_reduced_sm_corrected:", X_train_reduced_sm_corrected.shape)
print("Columns in X_train_reduced_sm_corrected:", X_train_reduced_sm_corrected.columns.tolist())

"""### Convert Boolean Columns to Integers for Statsmodels"""

print('Original dtypes of X_train_reduced_sm_corrected:')
print(X_train_reduced_sm_corrected.dtypes)

# Convert boolean columns to integer type (0 or 1)
for col in X_train_reduced_sm_corrected.columns:
    if X_train_reduced_sm_corrected[col].dtype == 'bool':
        X_train_reduced_sm_corrected[col] = X_train_reduced_sm_corrected[col].astype(int)

print('\nCorrected dtypes of X_train_reduced_sm_corrected:')
print(X_train_reduced_sm_corrected.dtypes)

"""### Fit Reduced Logistic Regression Model using Statsmodels"""

logit_model_reduced_corrected = sm.Logit(y_train, X_train_reduced_sm_corrected)
logit_model_reduced_corrected_result = logit_model_reduced_corrected.fit(maxiter=1000, disp=False)

print("Corrected reduced Logit model fitted successfully.")

"""### Display Coefficients and Odds Ratios for Reduced Model"""

import numpy as np

# Get the coefficients from the fitted model
coefficients = logit_model_reduced_corrected_result.params

# Calculate the odds ratios by exponentiating the coefficients
odds_ratios = np.exp(coefficients)

# Create a DataFrame to display coefficients and odds ratios
odds_ratios_df = pd.DataFrame({
    'Predictor': coefficients.index,
    'Coefficient': coefficients.values,
    'Odds_Ratio': odds_ratios.values
})

# Sort by Odds Ratio for better readability
odds_ratios_df = odds_ratios_df.sort_values(by='Odds_Ratio', ascending=False)

print("Coefficients and Odds Ratios from the corrected reduced Logit model:")
display(odds_ratios_df)

"""### Display Full Summary of Reduced Logit Model"""

print(logit_model_reduced_corrected_result.summary())

"""### Create Dissertation Table 4.5"""

import pandas as pd
import numpy as np

# Extract coefficients, p-values, and odds ratios
coefficients = logit_model_reduced_corrected_result.params
p_values = logit_model_reduced_corrected_result.pvalues

odds_ratios = np.exp(coefficients)

# Create the DataFrame for the table
table_data = pd.DataFrame({
    'Predictor': coefficients.index,
    'Coefficient': coefficients.values,
    'Odds Ratio': odds_ratios.values,
    'p-value': p_values.values
})

# Format p-values as '<0.001' or actual value
table_data['p-value'] = table_data['p-value'].apply(lambda x: '<0.001' if x < 0.001 else round(x, 3))

# Sort for better readability, similar to the example
table_data = table_data.sort_values(by='Coefficient', ascending=False).reset_index(drop=True)

# Display the table
print("Dissertation Table 4.5: Logistic Regression Coefficients, Odds Ratios, and P-values")
display(table_data)

"""### Export Dissertation Table 4.5"""

table_data.to_excel(
    "Table_4_5_Logistic_Regression_Results.xlsx",
    index=False
)

print("Dissertation Table 4.5 exported successfully to 'Table_4_5_Logistic_Regression_Results.xlsx'.")

"""### Visualize Odds Ratios of Reduced Model Predictors"""

import matplotlib.pyplot as plt
import seaborn as sns

# Exclude the 'const' variable for plotting as it's an intercept term
odds_ratios_to_plot = odds_ratios_df[odds_ratios_df['Predictor'] != 'const'].copy()

# Sort by Odds Ratio for plotting
odds_ratios_to_plot = odds_ratios_to_plot.sort_values(by='Odds_Ratio', ascending=True)

# Create a color map for visualization: blue for odds ratio > 1 (increased odds), red for < 1 (decreased odds)
odds_ratios_to_plot['color'] = odds_ratios_to_plot['Odds_Ratio'].apply(lambda x: 'skyblue' if x > 1 else 'lightcoral')

# Visualize the odds ratios
plt.figure(figsize=(12, 8))
sns.barplot(
    x='Odds_Ratio',
    y='Predictor',
    hue='Predictor', # Assign 'Predictor' to hue for coloring
    data=odds_ratios_to_plot,
    palette=odds_ratios_to_plot['color'].tolist(),
    legend=False # Set legend to False to avoid duplicate legend
)
plt.title('Odds Ratios of Predictors for Binary Outcome (Excluding Intercept)')
plt.xlabel('Odds Ratio (exp(Coefficient))')
plt.ylabel('Predictor')
plt.axvline(x=1, color='gray', linestyle='--', linewidth=0.8, label='Odds Ratio = 1 (No Effect)')
plt.legend()
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""## 4.4 Calibration Analysis"""

from sklearn.calibration import calibration_curve
import matplotlib.pyplot as plt

prob_true, prob_pred = calibration_curve(
    y_test,
    y_pred_proba,
    n_bins=10
)

plt.figure(figsize=(8,6))

plt.plot(
    prob_pred,
    prob_true,
    marker='o',
    label='Logistic Regression'
)

plt.plot(
    [0,1],
    [0,1],
    linestyle='--',
    label='Perfect Calibration'
)

plt.xlabel('Predicted Probability')
plt.ylabel('Observed Proportion')

plt.title('Calibration Curve')

plt.legend()

plt.savefig(
    'Figure_4_4_Calibration_Curve.png',
    dpi=300,
    bbox_inches='tight'
)

print("Figure 4.4 Calibration Curve saved to 'Figure_4_4_Calibration_Curve.png'.")

plt.show()

"""### Calculate Brier Score"""

from sklearn.metrics import brier_score_loss

brier = brier_score_loss(
    y_test,
    y_pred_proba
)

print("Brier Score:", round(brier,4))

"""### Calculate Calibration Intercept and Slope"""

import numpy as np
import statsmodels.api as sm

# Convert predicted probabilities to log-odds (logits)
logit_pred = np.log(
    y_pred_proba / (1 - y_pred_proba)
)

# Fit a logistic regression model with the true outcomes and predicted log-odds
calibration_model = sm.Logit(
    y_test,
    sm.add_constant(logit_pred) # Add a constant for the intercept
).fit(disp=False) # disp=False suppresses iteration details

print(calibration_model.summary())

# Extract the intercept and slope
intercept = calibration_model.params[0]
slope = calibration_model.params[1]

print("\nCalibration Intercept:", round(intercept, 4))
print("Calibration Slope:", round(slope, 4))

"""### Verify Columns for Calibration Analysis (Redundant Check)"""

print('Percent Achieved Diagnostic Change' in X.columns)
print('binary_outcome' in X.columns)

"""### Create Dissertation Table 4.6 (Calibration Measures)"""

table_4_6 = pd.DataFrame({
    'Measure': [
        'Calibration Slope',
        'Calibration Intercept',
        'Brier Score'
    ],
    'Value': [
        round(slope, 4),
        round(intercept, 4),
        round(brier, 4)
    ]
})
display(table_4_6)

"""### Export Dissertation Table 4.6"""

table_4_6.to_excel(
    "Table_4_6_Calibration_Measures.xlsx",
    index=False
)
print("Table 4.6 exported successfully to 'Table_4_6_Calibration_Measures.xlsx'.")

"""### Identify Columns Containing 'score', 'change', 'difference', 'effect'"""

for col in df.columns:
    if 'score' in col.lower() or 'change' in col.lower() or 'difference' in col.lower() or 'effect' in col.lower():
        print(col)

"""### Define Features (X_linear) and Target (y_linear) for Linear Regression

## 4.5 Linear Regression Model Development
"""

X_linear = X.copy()
y_linear = df['Percent Achieved Diagnostic Change']

print("X_linear shape:", X_linear.shape)
print("y_linear shape:", y_linear.shape)

"""### Split Data for Linear Regression"""

from sklearn.model_selection import train_test_split

X_train_lr, X_test_lr, y_train_lr, y_test_lr = train_test_split(
    X_linear,
    y_linear,
    test_size=0.20,
    random_state=42
)

print("Training set shape:", X_train_lr.shape)
print("Testing set shape:", X_test_lr.shape)

"""### Train Linear Regression Model"""

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()

lin_reg.fit(
    X_train_lr,
    y_train_lr
)

print("Linear Regression model trained successfully.")

"""### Make Predictions with Linear Regression Model"""

y_pred_lr = lin_reg.predict(X_test_lr)

"""### Evaluate Linear Regression Model Performance"""

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

r2 = r2_score(y_test_lr, y_pred_lr)

mae = mean_absolute_error(
    y_test_lr,
    y_pred_lr
)

rmse = np.sqrt(
    mean_squared_error(
        y_test_lr,
        y_pred_lr
    )
)

print("R²:", round(r2,4))
print("MAE:", round(mae,4))
print("RMSE:", round(rmse,4))

# Create a DataFrame for the metrics
table_4_7 = pd.DataFrame({
    'Metric': ['R²', 'MAE', 'RMSE'],
    'Value': [round(r2, 4), round(mae, 4), round(rmse, 4)]
})

# Display and export to Excel
display(table_4_7)

table_4_7.to_excel(
    "Table_4_7_Linear_Regression_Performance.xlsx",
    index=False
)

print("Table 4.7 exported successfully to 'Table_4_7_Linear_Regression_Performance.xlsx'.")

"""### Residual Plot"""

import matplotlib.pyplot as plt

residuals = y_test_lr - y_pred_lr

plt.figure(figsize=(8,6))

plt.scatter(
    y_pred_lr,
    residuals,
    alpha=0.5
)

plt.axhline(
    y=0,
    linestyle='--',
    color='red'
)

plt.xlabel("Predicted Values")
plt.ylabel("Residuals")

plt.title("Figure 4.5 Residual Plot - Linear Regression")

plt.savefig(
    'Figure_4_5_Residual_Plot.png',
    dpi=300,
    bbox_inches='tight'
)

print("Figure 4.5 Residual Plot saved to 'Figure_4_5_Residual_Plot.png'.")
plt.show()

"""### Residual Distribution Histogram"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.hist(
    residuals,
    bins=30,
    edgecolor='black'
)

plt.xlabel("Residuals")
plt.ylabel("Frequency")

plt.title("Figure 4.6 Residual Distribution - Linear Regression")

plt.savefig(
    'Figure_4_6_Residual_Distribution.png',
    dpi=300,
    bbox_inches='tight'
)

print("Figure 4.6 Residual Distribution saved to 'Figure_4_6_Residual_Distribution.png'.")
plt.show()

"""### Q-Q Plot of Residuals"""

import matplotlib.pyplot as plt
import scipy.stats as stats

plt.figure(figsize=(8,6))

stats.probplot(
    residuals,
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot of Linear Regression Residuals")

plt.show()

"""### Display Top Linear Regression Coefficients"""

coef_df_lr = pd.DataFrame({
    'Predictor': X_linear.columns,
    'Coefficient': lin_reg.coef_
})

coef_df_lr = coef_df_lr.sort_values(
    by='Coefficient',
    ascending=False
)

print("Linear Regression Coefficients (Top 20):")
display(coef_df_lr.head(20))

"""### Prepare Reduced Features for Linear Regression (OLS)"""

linear_vars = [
    'Veteran Percent',
    'Female Percent',
    'baseline_z',
    'treatment_duration',
    'Trauma Type_Combat-related',
    'Trauma Type_Mixed'
]

X_linear_reduced = df[linear_vars]

y_linear = df['Percent Achieved Diagnostic Change']

print("X_linear_reduced shape:", X_linear_reduced.shape)
print("y_linear shape:", y_linear.shape)

"""### Fit Reduced Linear Regression Model using Statsmodels (OLS)"""

import statsmodels.api as sm

# Create a copy to avoid SettingWithCopyWarning
X_linear_reduced_copy = X_linear_reduced.copy()

# Ensure boolean columns are converted to int for statsmodels
for col in X_linear_reduced_copy.columns:
    if X_linear_reduced_copy[col].dtype == 'bool':
        X_linear_reduced_copy.loc[:, col] = X_linear_reduced_copy[col].astype(int)

X_linear_reduced_sm = sm.add_constant(X_linear_reduced_copy)

ols_model = sm.OLS(
    y_linear,
    X_linear_reduced_sm
).fit()

print(ols_model.summary())

"""### Display Coefficients, Standard Errors, and P-values for Reduced OLS Model"""

results_table = pd.DataFrame({
    'Predictor': ols_model.params.index,
    'Coefficient': ols_model.params.values,
    'Standard Error': ols_model.bse.values,
    'p-value': ols_model.pvalues.values
})

# Format p-values as '<0.001' or actual value
results_table['p-value'] = results_table['p-value'].apply(lambda x: '<0.001' if x < 0.001 else round(x, 3))

display(results_table)

"""### Export Dissertation Table 4.8"""

results_table.to_excel(
    "Table_4_8_Linear_Regression_Coefficients.xlsx",
    index=False
)

print("Export complete.")

"""### Calculate Variance Inflation Factor (VIF) for Reduced Model"""

from statsmodels.stats.outliers_influence import variance_inflation_factor

# Calculate VIF for each predictor in X_linear_reduced_sm
vif_data = pd.DataFrame()
vif_data['Predictor'] = X_linear_reduced_sm.columns
vif_data['VIF'] = [variance_inflation_factor(X_linear_reduced_sm.values, i) for i in range(X_linear_reduced_sm.shape[1])]

# Sort the DataFrame by VIF values in descending order for easier interpretation
vif_data = vif_data.sort_values(by='VIF', ascending=False).reset_index(drop=True)

print("Variance Inflation Factor (VIF) for Predictors in Reduced Linear Regression Model:")
display(vif_data)

"""### Export Dissertation Table 4.9 (VIF Results)"""

vif_data.to_excel(
    "Table_4_9_VIF_Results.xlsx",
    index=False
)

print("Variance Inflation Factor (VIF) results exported successfully to 'Table_4_9_VIF_Results.xlsx'.")

"""## 4.6 Decision Curve Analysis (DCA)"""

import numpy as np
import pandas as pd

thresholds = np.arange(0.01, 0.99, 0.01)

net_benefits = []

N = len(y_test)

for pt in thresholds:

    predictions = (y_pred_proba >= pt).astype(int)

    TP = ((predictions == 1) & (y_test == 1)).sum()
    FP = ((predictions == 1) & (y_test == 0)).sum()

    # Calculate Net Benefit (NB)
    # The formula is: NB = (TP / N) - (FP / N) * (pt / (1 - pt))
    # Where pt is the threshold probability (or probability of treatment)
    # and pt / (1 - pt) is the odds of harm (relative weight of false positives)
    nb = (TP / N) - (FP / N) * (pt / (1 - pt))

    net_benefits.append(nb)

dca_results = pd.DataFrame({
    'Threshold Probability': thresholds,
    'Net Benefit': net_benefits
})

print("Net Benefit values for the Prediction Model calculated.")
display(dca_results.head())

"""### Calculate Net Benefit for Prediction Model"""

prevalence = y_test.mean()

treat_all_nb = []

for pt in thresholds:
    # Net benefit for treating all individuals
    # NB_all = prevalence - (1 - prevalence) * (pt / (1 - pt))
    nb_all = prevalence - (1 - prevalence) * (pt / (1 - pt))
    treat_all_nb.append(nb_all)

print("Net Benefit values for 'Treat All' strategy calculated.")

"""### Calculate Net Benefit for 'Treat All' Strategy"""

# The net benefit for treating no individuals is always zero
treat_none_nb = np.zeros(len(thresholds))

print("Net Benefit values for 'Treat None' strategy defined (all zeros).")

"""### Define Net Benefit for 'Treat None' Strategy"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,7))

plt.plot(
    thresholds,
    net_benefits,
    label='Prediction Model',
    linewidth=2
)

plt.plot(
    thresholds,
    treat_all_nb,
    linestyle='--',
    label='Treat All'
)

plt.plot(
    thresholds,
    treat_none_nb,
    linestyle=':',
    label='Treat None'
)

plt.xlabel('Threshold Probability')

plt.ylabel('Net Benefit')

plt.title('Figure 4.7 Decision Curve Analysis (Enhanced)')

plt.legend()

plt.grid(True)

# --- FIX: Set clinically relevant axis limits ---
plt.xlim(0.0, 0.5) # Limit X-axis to 0% to 50% risk threshold
plt.ylim(-0.02, prevalence + 0.05) # Zoom Y-axis around the prevalence rate
# -------------------------------------------------

plt.savefig(
    'Figure_4_7_Decision_Curve_Analysis_Enhanced.png',
    dpi=300,
    bbox_inches='tight'
)

print("Figure 4.7 Decision Curve Analysis Plot (Enhanced) saved to 'Figure_4_7_Decision_Curve_Analysis_Enhanced.png'.")
plt.show()

"""### Create Dissertation Table 4.10 (DCA Results for Selected Thresholds)"""

selected_thresholds = [0.10, 0.20, 0.30, 0.40, 0.50]

table_410 = dca_results[
    dca_results['Threshold Probability'].round(2).isin(selected_thresholds)
].copy()

print("Table 4.10 created for selected thresholds:")
display(table_410)

"""### Export Dissertation Table 4.10"""

table_410.to_excel(
    "Table_4_10_DCA_Results.xlsx",
    index=False
)

print("Table 4.10 exported successfully to 'Table_4_10_DCA_Results.xlsx'.")

